name: teoria-juegos
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy>=1.26
  - scipy>=1.12
  - matplotlib>=3.8
  - networkx>=3.2
  - jupyter
  - jupyterlab>=4.0
  - ipywidgets>=8.0
  - pip:
    - nashpy==0.0.21
    - axelrod==4.13.0
